env:
  TERM: xterm-256color

live_config_reload: true

selection:
  save_to_clipboard: true

window:
  padding:
    x: 8
    y: 8
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

background_opacity: 1.0

colors:
  primary:
    background: '0x1f1f24'
    foreground: '0xFAF3D1'

  cursor:
    text: '0x000000'
    cursor: '0xFC1EBD'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'

font:
  size: 7.4
  normal:
    family: Fira Code Retina
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic
  offset:
    x: 0
    y: 1

scrolling:
  history: 8000
  multiplier: 3

cursor:
  style: Beam

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
