#!/usr/bin/env bash
# Creates python file with shebang and main, then sets ux permissions
# createpy [FILENAME]
function pycreate() {
    PYFILE="$1"
    if [[ $PYFILE == *".py"* ]]
    then
        touch "$PYFILE"
        echo "#!/usr/bin/env python3" >> "$PYFILE"
        echo "" >> "$PYFILE"
        echo 'if __name__ == "__main__":' >> "$PYFILE"
        echo "    pass" >> "$PYFILE"
        chmod u+x "$PYFILE"
        vim "$PYFILE"
    else
        touch "$PYFILE.py"
        PYFILEPY="$PYFILE.py"
        echo "#!/usr/bin/env python3" >> "$PYFILEPY"
        echo "" >> "$PYFILEPY"
        echo 'if __name__ == "__main__":' >> "$PYFILEPY"
        echo "    pass" >> "$PYFILEPY"
        chmod u+x "$PYFILEPY"
        vim "$PYFILEPY"
    fi
}
