#!/usr/bin/env bash
alias lll='ls -la'
alias ll='ls -l'
alias v='vim'
alias rbr='source ~/.bashrc'
alias cls='printf "\033c"'
alias hgcc='gcc -Wall -Werror -Wextra -pedantic'
alias mynetip='curl "ifconfig.me";echo'
alias ux='chmod u+x'
alias ..='cd ..'

# Bash behavior
#  -> Tab auto-complete
bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"

# Git
alias gpush='git push origin'
alias grm='git rm'
alias mpush='git push origin master'
alias gstat='git status .'
alias gdiff='git diff'
alias gadd='git add'
alias gpull='git pull origin'
alias mpull='git pull origin master'

# Python
alias venv_a='source venv/bin/activate'
alias venv_d='deactivate'

# Git Funcs
gcomm() {
    GITMESSAGE="$*"
    git commit -m "$GITMESSAGE"
}
