#!/usr/bin/env bash
# VIM
sudo pacman -S vim

# git
sudo pacman -S git

# Docker on Arch setup
sudo pacman -S docker
sudo newgrp docker
systemctl enable docker
systemctl start docker

# Photoshop alternative
sudo pacman -S krita

# yay for AUR
git clone "https://aur.archlinux.org/yay.git"
cd yay
makepkg -si

# pass, password-store
sudo pacman -S pass

# snap + slack + discord
sudo pacman -S snapd
sudo snap install slack --classic
sudo snap install discord

# Install hiragana keyboard
sudo pacman -S adobe-source-han-sans-jp-fonts otf-ipafont
yay -S ttf-monapo
sudo pacman -S ibus ibus-anthy
# .xprofile
# export GTK_IM_MODULE='ibus'
# export QT_IM_MODULE='ibus'
# export XMODIFIERS=@im='ibus'
# ibus-daemon -drx
# /etc/locale.gen
# ja_JP.UTF-8

# Enabling U2F for yubikey
# https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux
cd /etc/udev/rules.d/
sudo wget "https://raw.githubusercontent.com/Yubico/libu2f-host/master/70-u2f.rules"
