#!/usr/bin/env bash
# Arch package checker
function checkpass() {
  if ! pacman -Qs pass > /dev/null;
  then
    echo -e " > Pass not found\n > Installing pass..."
    sudo pacman -S pass
    exit 1
  fi
}
# Checks last command's status
# source globals before sourcing functions if using this
function status_check {
  if [[ $? == 0 ]];then echo -en " > ${G}success${NC}";else echo -en " > ${R}fail${NC}";fi
}
