#! /bin/sh

# kill any existing apps
killall -q picom
killall -q fehbg
killall -q dunst
killall -q polybar
killall -q ibus-daemon

# bspwm stuff
if [[ $(xrandr -q | grep -w connected | grep "HDMI-1") ]]
then
  bspc monitor eDP-1 -d 1 2 3 4 5 6
  bspc monitor HDMI-1 -d 7 8 9 0
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi
bspc config top_padding          0
bspc config border_width         1
bspc config window_gap          14
bspc config split_ratio          0.51
bspc config focused_border_color "#3DE1CC"
bspc config presel_feedback_color "#1ABB9B"
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config single_monocle            true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer     true ## this lets the cursor focus a window

# apps
pgrep -x sxhkd > /dev/null || sxhkd &
ibus-daemon -drx
picom -b
~/.fehbg &
dunst &
setxkbmap -layout us &
polybar leftbar &
polybar midbar &
polybar rightbar &
if [[ $(xrandr -q | grep -w connected | grep "HDMI-1") ]]
then
  polybar midbar2 &
fi
