#!/usr/bin/env bash
#+ Nvim-nightly install script
curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -o /tmp/nvim-nightly
chmod +x /tmp/nvim-nightly
sudo mv /tmp/nvim-nightly /usr/local/bin
./usr/local/bin/nvim-nightly
#+ Checking if nvim-nightly fails
if [[ $? == 0 ]];
then
  echo -en " > Installed nvim-nightly"
else
  echo -en " > Fixing Nvim Error..."
  sudo ./usr/local/bin/nvim-nightly --appimage-extract
  sudo mv /usr/local/bin/nvim-nightly /tmp
  sudo ln -s /usr/local/bin/squashfs-root/usr/bin/nvim-nightly /usr/local/bin/nvim-nightly
  echo -en " > Original nvim-nightly is in /tmp"
  echo -en " > If you still cannot use nvim-nightly, please restore the original and manually ins
tall again with --appimage-extract"
fi
