#!/usr/bin/env bash
# Creates Nginx default file
echo "server {" >> default
echo -e "\tlisten 80;" >> default
echo -e "\tserver_name [SERVER_NAME];\n" >> default
echo -e "\tlocation /static {" >> default
echo -e "alias /home/[USERNAME]/[PROJECT_FOLDER]/static;" >> default
echo -e "\t}\n" >> default
echo -e "location / {" >> default
echo -e "proxy_pass http://localhost:8000;" >> default
echo -e "include /etc/nginx/proxy_params;" >> default
echo -e "proxy_redirect off;" >> default
echo -e "\t}\n" >> default
echo "}" >> default
