#!/usr/bin/env bash
echo "[program: [PROJECT_NAME]]" >> [PROJECT_NAME].conf
echo "directory=[PATH_TO_PROJECT]" >> [PROJECT_NAME.conf]
echo "command=[PATH_TO_PROJECT/venv/bin/gunicorn] -w [NUMER_OF_WORKERS] [RUN_FILE]:[APP_VARIABLE]" >> [PROJECT_NAME.conf]
echo "autostart=true" >> [PROJECT_NAME.conf]
echo "autorestart=true" >> [PROJECT_NAME.conf]
echo "stopasgroup=true" >> [PROJECT_NAME.conf]
echo "killasgroup=true" >> [PROJECT_NAME.conf]
echo ""stderr_logfile=/var/log/[PROJECT_FOLDER]/[PROJECT_NAME].err.log >> [PROJECT_NAME.conf]
echo "stdout_logfile=/var/log/[PROJECT_FOLDER]/[PROJECT_NAME].out.log" >> [PROJECT_NAME.conf]

sudo mkdir -p /var/log/[PROJECT_FOLDER]
sudo touch /var/log/[PROJECT_FOLDER]/[PROJECT_NAME].err.log
sudo touch /var/log/[PROJECT_FOLDER]/[PROJECT_NAME].out.log
sudo supervisorctl reload
