#!/usr/bin/env bash
# $1 = srcfile, $2 = user, $3 = ip, $4 = port, $5 = dest
if [[ $# == 3 ]]
then
    scp "$1" "$2@$3:~/"
elif [[ $4 == "none" ]]
then
    scp -P "$5" "$1" "$2@$3:~/"
elif [[ $# == 4 ]]
then
    scp "$1" "$2@$3:~/$4"
elif [[ $# == 5 ]]
then
    scp -P "$5" "$1" "$2@$3:~/$4"
else
    echo "Arguments invalid."
fi
