#!/bin/bash
declare -A COMPONENT_NAME
COMPONENT_PATH="/home/harukai/00/dotfiles/scripts/themer/test.conf"
COMPONENT_TAG_START="# Themer start"
COMPONENT_TAG_END="# Themer end"
#+ ["PATTERN"]="NEWCOLOR"
COMPONENT_NAME=(
  ["color0"]="color1 #FFF"
  ["color8"]="color2 #000"
)
