[[ $- != *i* ]] && return
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

alias ls='ls --color=auto'
alias ll='exa -lg --icons'
alias lll='exa -lga'
alias v='nvim'
alias ..='cd ..'
alias ux='chmod u+x'
alias venva='source venv/bin/activate'
alias passc='pass -c'
alias mkdir='mkdir -p'
alias cat='bat --style=header,grid'
alias ssh='kitten ssh'

alias gadd='git add'
alias gdiff='git diff'
alias mpush='git push origin master'
alias gstat='git status'
function gcom() {
    GITMESSAGE="$*"
    git commit -m "$GITMESSAGE"
}

alias neofetch='neofetch --backend kitty --source /home/kokopi/pictures/neofetch_0.png --size 320'

bind 'TAB:menu-complete'
bind 'set show-all-if-ambiguous on'
eval "$(starship init bash)"


function fsize() {
  du -sh "$1"
}

export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --ignore-file ~/.fzfignore'
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}' --preview-window down
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

alias ibus-setup="PYTHON=/usr/bin/python ibus-setup"
