# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Custom Alias Base
alias cp="cp -i"
alias df="df -h"
alias v="nvim"
alias ..="cd .."
alias ll="exa -lg"
alias lll="exa -lga"
alias ux="chmod u+x"
alias passc="pass -c"
alias venva="source venv/bin/activate"
alias venvd="deactivate"
alias gstat="git status"
alias gdiff="git diff"
alias gadd="git add"
alias mpush="git push origin master"
alias recentlyadded="grep -i installed /var/log/pacman.log"
# Custom Alias Packages
alias ccat="/usr/bin/cat"
alias cat="bat --style=header,grid"
### Custom Functions ###
# File size
function fsize() {
  du -sh "$1"
}
# Git commit -m
function gcomm() {
    GITMESSAGE="$*"
    git commit -m "$GITMESSAGE"
}
### Behavior ###
bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"
eval "$(starship init bash)"

### Japanese Keyboard ###
export GTK\_IM\_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT\_IM\_MODULE=ibus

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

if [ "$(echo $PATH | grep -c '.pyenv')" == "0" ]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
fi
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
alias apitester="python /home/harukai/.harukai.scripts/apitester/api.py"
alias apitesteredit="nvim /home/harukai/.harukai.scripts/apitester/profile_data.py"

if [ "$(echo $_JAVA_AWT_WM_NONREPARENTING)" != "1" ]; then
  export _JAVA_AWT_WM_NONREPARENTING=1
fi
