#!/usr/bin/env bash
# VIM
sudo pacman -S --noconfirm vim

# git
sudo pacman -S --noconfirm git

# Docker on Arch setup
sudo pacman -S --noconfirm docker
sudo newgrp docker
systemctl enable docker
systemctl start docker

# Photoshop alternative
sudo pacman -S --noconfirm krita

# yay for AUR
git clone "https://aur.archlinux.org/yay.git"
cd yay
makepkg -si

# pass, password-store
sudo pacman -S --noconfirm pass

# snap + discord
sudo pacman -S --noconfirm snapd
sudo systemctl start snapd.service
sudo snap refresh
sudo snap install discord

# Slack
git clone https://aur.archlinux.org/slack-desktop.git
cd slack-desktop
sudo pacman -S --noconfirm gconf
sudo pacman -S --noconfirm libcurl-compat
makepkg
sudo pacman -U --noconfirm *.pkg.tar.xz
cd ..
rm -rf slack-desktop


# Install hiragana keyboard
sudo pacman -S --noconfirm adobe-source-han-sans-jp-fonts otf-ipafont
yay -S ttf-monapo
sudo pacman -S --noconfirm ibus ibus-anthy
# .xprofile
# export GTK_IM_MODULE='ibus'
# export QT_IM_MODULE='ibus'
# export XMODIFIERS=@im='ibus'
# ibus-daemon -drx
# /etc/locale.gen
# ja_JP.UTF-8
# Set anthy in keyboards after

# Enabling U2F for yubikey
# https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux
cd /etc/udev/rules.d/
sudo wget "https://raw.githubusercontent.com/Yubico/libu2f-host/master/70-u2f.rules"

# Install ndcu - file size checker
sudo pacman -S --noconfirm ncdu

# Hardware GUI checker
sudo pacman -S --noconfirm hardinfo

# OBS
sudo pacman -S --noconfirm obs

# Unzip - Zip
sudo pacman -S --noconfirm unzip
sudo pacman -S --noconfirm zip

# PIA
# https://www.privateinternetaccess.com/installer/x/download_installer_linux
# sh run-...
